package blok5afvink6;

import java.awt.*;
import javax.swing.*;

public class AminoAcidReader extends javax.swing.JFrame {

    static char[] polair = new char[]{'Q', 'N', 'H', 'S', 'T', 'Y', 'C'};
    static char[] aminoarray = new char[]{'A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'};
    static public String Amino;
    static public String acode;
    static char[] letter;
    static float polairint;
    static float nonpolairint;
    static int polaircount;
    static int nonpolaircount;

    /**
     * Creates new form AminoAcidReader
     */
    public AminoAcidReader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AminoArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        SeqLabel = new javax.swing.JLabel();
        AnalyseButton = new javax.swing.JButton();
        PercentLabel = new javax.swing.JLabel();
        PercentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AminoAcidArea = new javax.swing.JTextArea();
        PolairText = new javax.swing.JTextField();
        ApolairText = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        AminoArea.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SeqLabel.setText("Sequentie");

        AnalyseButton.setText("Analyseer");
        AnalyseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseButtonActionPerformed(evt);
            }
        });

        PercentLabel.setText("Percentage");

        javax.swing.GroupLayout PercentPanelLayout = new javax.swing.GroupLayout(PercentPanel);
        PercentPanel.setLayout(PercentPanelLayout);
        PercentPanelLayout.setHorizontalGroup(
            PercentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        PercentPanelLayout.setVerticalGroup(
            PercentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        AminoAcidArea.setColumns(20);
        AminoAcidArea.setRows(5);
        jScrollPane1.setViewportView(AminoAcidArea);

        PolairText.setText("Polair");
        PolairText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolairTextActionPerformed(evt);
            }
        });

        ApolairText.setText("Apolair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SeqLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AnalyseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(PercentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ApolairText)
                                    .addComponent(PolairText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(PercentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AnalyseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeqLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PercentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PolairText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(ApolairText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PercentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalyseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseButtonActionPerformed

        String amino = AminoAcidArea.getText();
        char[] aa = amino.toCharArray();
        for (int i = 0; i < aa.length; i++) {
            if (new String(aminoarray).indexOf(aa[i]) != -1) {
                for (int z = 0; z < polair.length; z++) {
                    if (aa[i] == polair[z]) {
                        polaircount++;
                    }
                }
            } else if (new String(aminoarray).indexOf(aa[i]) == -1) {
                JOptionPane.showMessageDialog(null, "Er staat een niet aminozuur letter in!");
            }
                        
            polairint = (((float) polaircount / aa.length) * 100);
            nonpolairint = (100 - (float) polairint);
            
            Graphics paper = PercentPanel.getGraphics();
            paper.setColor(Color.blue);
            paper.fillRect(10, 40, (int) polairint * 5, 20);
            PolairText.setText("Polair " + polairint + "%");

            paper.setColor(Color.yellow);
            paper.fillRect(10, 80, (int) nonpolairint * 5, 20);
            ApolairText.setText("Apolair " + nonpolairint + "%");

    }//GEN-LAST:event_AnalyseButtonActionPerformed
    }

    private void PolairTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolairTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PolairTextActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AminoAcidReader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AminoAcidReader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AminoAcidReader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AminoAcidReader.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AminoAcidReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AminoAcidArea;
    private javax.swing.JScrollPane AminoArea;
    private javax.swing.JButton AnalyseButton;
    private javax.swing.JTextField ApolairText;
    private javax.swing.JLabel PercentLabel;
    private javax.swing.JPanel PercentPanel;
    private javax.swing.JTextField PolairText;
    private javax.swing.JLabel SeqLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
